<#
.SYNOPSIS
Calculates the total size of a given folder, using a cache if available.

.DESCRIPTION
This script first checks for a cached folder size generated by the SizeCacheService.
If a valid cache entry is found, it displays the size instantly. Otherwise, it
recursively calculates the size on demand.

.PARAMETER Path
The full path to the folder you want to measure.
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true, ValueFromPipeline = $true, Position = 0)]
    [string]$Path
)

# --- Configuration ---
# Path to the cache file generated by the size-cache-service.exe
$cacheFilePath = Join-Path $PSScriptRoot "..\src\SizeCacheService\bin\Release\net8.0\sizecache.json"


process {
    $upperPath = $Path.ToUpperInvariant()

    # 1. Try to get the size from the cache
    if (Test-Path $cacheFilePath) {
        $cacheContent = Get-Content $cacheFilePath | ConvertFrom-Json
        if ($cacheContent.PSObject.Properties.Match($upperPath).Count -gt 0) {
            $entry = $cacheContent.$upperPath
            $cachedSize = $entry.Size
            $lastCalculated = $entry.LastCalculatedUtc

            $humanReadableSize = switch ($cachedSize) {
                { $_ -ge 1TB } { "{0:N2} TB" -f ($_ / 1TB) }
                { $_ -ge 1GB } { "{0:N2} GB" -f ($_ / 1GB) }
                { $_ -ge 1MB } { "{0:N2} MB" -f ($_ / 1MB) }
                { $_ -ge 1KB } { "{0:N2} KB" -f ($_ / 1KB) }
                default        { "{0} Bytes" -f $_ }
            }

            Write-Host "Folder Path: $Path"
            Write-Host "Total Folder Size: $humanReadableSize (Cached)"
            Write-Host "Total Bytes: $cachedSize"
            Write-Host "Last Calculated: $([datetime]$lastCalculated).ToLocalTime()"
            
            Write-Host ""
            Read-Host "Press Enter to close..."
            return
        }
    }

    # 2. If not in cache, calculate on demand
    Write-Host "No cache entry found. Calculating size of folder: $Path"
    Write-Host "This may take a while for large folders..."

    try {
        $totalSize = (Get-ChildItem -Path $Path -Recurse -File -Force -ErrorAction Stop | Measure-Object -Property Length -Sum).Sum
    }
    catch {
        Write-Error "An error occurred while calculating the folder size. Check permissions. Error: $_"
        Read-Host "Press Enter to close..."
        return
    }

    $humanReadableSize = switch ($totalSize) {
        { $_ -ge 1TB } { "{0:N2} TB" -f ($_ / 1TB) }
        { $_ -ge 1GB } { "{0:N2} GB" -f ($_ / 1GB) }
        { $_ -ge 1MB } { "{0:N2} MB" -f ($_ / 1MB) }
        { $_ -ge 1KB } { "{0:N2} KB" -f ($_ / 1KB) }
        default { "{0} Bytes" -f $_ }
    }

    Write-Host ""
    Write-Host "Total Folder Size: $humanReadableSize"
    Write-Host "Total Bytes: $totalSize"
    
    Write-Host ""
    Read-Host "Press Enter to close..."
}
